import { Cliente } from '../models/cliente';
/*
export const CLIENTES: Cliente[] = [
  {
    id: 1,
    nombre: 'Easter',
    apellido: 'Baudinelli',
    createAt: '2023-02-01',
    email: 'ebaudinelli0@nyu.edu',
  },
  {
    id: 2,
    nombre: 'Neddy',
    apellido: 'Karpol',
    createAt: '2022-06-05',
    email: 'nkarpol1@hhs.gov',
  },
  {
    id: 3,
    nombre: 'Ardisj',
    apellido: 'Silbermann',
    createAt: '2022-09-17',
    email: 'asilbermann2@umn.edu',
  },
  {
    id: 4,
    nombre: 'Roddie',
    apellido: 'Joincey',
    createAt: '2023-03-28',
    email: 'rjoincey3@smugmug.com',
  },
  {
    id: 5,
    nombre: 'Wylma',
    apellido: 'Goeff',
    createAt: '2023-02-16',
    email: 'wgoeff4@shinystat.com',
  },
  {
    id: 6,
    nombre: 'Val',
    apellido: 'McGraw',
    createAt: '2022-08-12',
    email: 'vmcgraw5@phoca.cz',
  },
  {
    id: 7,
    nombre: 'Jolie',
    apellido: 'Whorall',
    createAt: '2023-01-19',
    email: 'jwhorall6@skyrock.com',
  },
  {
    id: 8,
    nombre: 'Jacinda',
    apellido: 'Sutor',
    createAt: '2023-02-14',
    email: 'jsutor7@seesaa.net',
  },
  {
    id: 9,
    nombre: 'Guillermo',
    apellido: 'Scott',
    createAt: '2022-08-26',
    email: 'gscott8@cam.ac.uk',
  },
  {
    id: 10,
    nombre: 'Janith',
    apellido: 'Stebbin',
    createAt: '2023-04-29',
    email: 'jstebbin9@fastcompany.com',
  },
  {
    id: 11,
    nombre: 'Culver',
    apellido: 'Skelington',
    createAt: '2022-06-16',
    email: 'cskelingtona@4shared.com',
  },
  {
    id: 12,
    nombre: 'Merralee',
    apellido: 'Pinsent',
    createAt: '2022-11-28',
    email: 'mpinsentb@omniture.com',
  },
  {
    id: 13,
    nombre: 'Jerry',
    apellido: 'Allwell',
    createAt: '2023-01-15',
    email: 'jallwellc@people.com.cn',
  },
  {
    id: 14,
    nombre: 'Bernard',
    apellido: 'Rosenbaum',
    createAt: '2022-07-30',
    email: 'brosenbaumd@nydailynews.com',
  },
  {
    id: 15,
    nombre: 'Dorri',
    apellido: 'Lismer',
    createAt: '2022-09-02',
    email: 'dlismere@google.it',
  },
];*/
